### ISSUE TITLE
Keys shifted from QMK Configurator

### ISSUE THREAD

**Issue by rmont881** [jurassic73/split89#1]
When flashing the firmware made from the QMK Configurator, all of they keys are shifted over as if the columns are misconfigured. For example, the backspace key is actually the =, the insert key is the backspace, etc. This happens on both the left and the right side. The rows seem to be right, the columns seem to be shifted left by one.

Tested both in a wired left hand keyboard, and flashing to an arduino and manually connecting the pins relating to the rows/columns.

**Comment by jurassic73** [comment]
You are right! I downloaded the hex file from the QMK configurator page and it shifted my keys as well. Not sure what happened here.  I had this working initially.  I will investigate.  Until then, I've uploaded a working hex file to keep you moving forward. I downloaded and configured this same hex file contents to both keyboard halfs per my method on the page and it works on my end.  Please give this a go.

https://github.com/jurassic73/split89#programming-the-controllers

**Comment by jurassic73** [comment]
I got the keyboard mapping corrected except I missed an update in the configurator mapped layout(separate repositories).  When you go to qmk configurator now and bring up the split89 layout, in the lower left corner the control key is configured as a shift key. If you change that to left control key and download the firmware you'll be good.

I submitted a pull request to fix that last key map bit.

Any chance you documented your build online? You're the first person to reach out it has built my keyboard design.  Would be really need to see pictures of it. 🙂

**Comment by rmont881** [comment]
Sweet, I'll give it a shot! I was helping with the build when we ran into this and that one wasn't documented, but I am building one myself right now I'll get this one documented and posted somewhere. Thanks for responding so quick with the hex file to unblock the build, that was super helpful!

**Comment by jurassic73** [comment]
Thanks for the patience and feedback!  I'm stoked folks are building this after putting it out there.  :)  I built three myself.  Gave one to my brother and we're both using them now as daily drivers.  Having you, as another builder, go through the process is helping me refine any opportunities in the documentation for future builders to have a smoother experience.  If you see anything else, please let me know.  Thanks.

**Comment by rmont881** [comment]
On that, in your write up you never posted where you get your headphone jack breakout boards. I couldn't find anything that looked similar so we got these(linked below) and then modeled a really simple backing brace and drilled the hole out to fit. I can upload the STL for it as well to give more options for anyone building in the future as well. Other than that part, everything else on this case was way nicer to build than any of the other 3d printed keyboards I've made. 

https://www.amazon.com/dp/B008SNZUYC?psc=1&ref=ppx_yo2_dt_b_product_details

**Comment by jurassic73** [comment]
Ah shoot... that was added later on.  Good catch and sorry.

(2) Tactile Micro vertical mount switch (6mmx6mmx8mm total height / 4.5mm button height) - Aliexpress

https://www.aliexpress.com/item/4000543708838.html?spm=a2g0s.9042311.0.0.27424c4dCLLkyk

**Comment by jurassic73** [comment]
Thanks for the kind words... this design was tweaked a bit as I built it and saw opportunities.  I put the dimensions in there too for the button.

**Comment by jurassic73** [comment]
(2) TRRS breakout boards 

https://www.aliexpress.com/wholesale?SearchText=trrs+audio+socket+breakout

**Comment by jurassic73** [comment]
Added an Amazon link as well for the TRRS boards.  Thanks for pointing this out! :)

**Comment by jurassic73** [comment]
Default keymap has been updated in the QMK configurator to generate firmware and confirmed as working.  Thanks for the feedback.

**Comment by pulsar256** [comment]
Ran into the issue of shifted columns with the official QMK configurator build today. Seems to be still an issue. HEX file embedded in this repo does not exhibit the behaviour. 

Shall I open a PR with notes that in the README? I might also add a couple of lines about the flashing process.

**Comment by jurassic73** [comment]
Someone changed my config. This was working a month or so ago. It's clear
that someone updated something to shift the keys. A for example is now on
Caps Lock.

https://config.qmk.fm/#/handwired/split89/LAYOUT

I've reached out on Discord to see about getting these changes rolled back.

Thanks for letting me know!

I added some verbiage regarding this on the split89 QMK configurator section as well as directly linked the hex file.

Would love to see your build added here: https://www.printables.com/model/75599-split89/comments :)

**Comment by pulsar256** [comment]
> Would love to see your build added here: https://www.printables.com/model/75599-split89/comments :)

will do! Had to tweak the MCU mounts a bit as well (pro micro with usb-c, dimensions of the jack breakout slightly off), will go into details in the comment.

**Comment by jurassic73** [comment]
> 

Great - thanks!

Working with the QMK devs on fixing up my keyboard layout. Needs some retooling to adhere to their standards correctly. It worked but something was not correct in such a way that my stuff broke with some cleanup they were doing. They provided guidance with how to fix so I'll work on this this weekend. Least you can move ahead with the hex file up there currently to get your keyboard going.
