### ISSUE TITLE
QMK Configurator still shifted right one

### ISSUE THREAD

**Issue by rmont881** [jurassic73/split89#2]
Finished building the second one of these and went to try out the changes to QMK Configurator and they are still shifted right, so I'm back on using the default hex you supplied.

**Comment by jurassic73** [comment]
Hi Robert,

Thanks for this update.  I had the firmware working on that site however
one of the QMK admins rearranged my code for some kind of optimization a
few days ago(without my request) and seems to have broken it in the
process. I will request it be rolled back.

**Comment by rmont881** [comment]
Awesome, thanks for the quick response!

**Comment by jurassic73** [comment]
Forgot to close this prior... This was fixed.
