### ISSUE TITLE
Low Profile Keys?

### ISSUE THREAD

**Issue by vkhurana** [jurassic73/split89#3]
Would it be possible to get the F3D/Source files for the housing? It would be useful to adapt the board for low-profile keys:
https://hexus.net/tech/news/peripherals/114314-cherry-announces-mx-low-profile-rgb-key-switches/

The dimensions of low profile keys is slightly smaller than regular full-profile keys:
```
... dimensions of 11.9 x 15.0 x 15.0mm (H x W x D). For the record a conventional MX switch measures 18.5 x 15.6 x 15.6mm (H x W x D) ...
```

I'd be happy to give it a shot and update the stls for low-profile keys.

**Comment by jurassic73** [comment]
They still fit in a 14mm x 14mm hole.  The overall dimension changed but not the hole size requirement.  There should be no adjustment required to use those. :)

**Comment by vkhurana** [comment]
Thank you! I'll print the reference square and give it a shot.
