### ISSUE TITLE
Left body requires supports for bolt pillars?

### ISSUE THREAD

**Issue by dgurchenkov** [jurassic73/split89#4]
Hi,

First, thank you for putting together this keyboard and instructions. This is an awesome project!

When trying to follow the instructions and print/build/assemble the keyboard, I seem to have found an issue that may require either updating the printing instructions, or perhaps some change to one or more .stl files. I am a newbie so this may just be my misunderstanding -- please feel free to close this issue.

The printing instructions in readme.md indicate that no supports need to be added when printing, with the exception of wrist pads. 
However, the split89_left_body.stl has elements (bolt pillars) that hang down from the main body but do not touch the base plate. "As-is" slicing in Cura produces a gcode file that is not printable, because the printer then tries to start printing those bold pillars "from the air" at some distance from the base plate, and the filament has nothing to adhere to. Please see an attached screenshot where I circled (in grey) the four columns in left_body.stl that do not touch the base plate.

Reproduction steps:
* I use Ender-3 v2 printer, Cura v 4.13.1, printing with generic PLA filament
* Open split89_left_body.stl in Cura, do not enable supports, slice, send directly to the printer. 
* The bolt pillars in the middle of the body do not get printed. Extruder extracts the filament that hangs in the air.
* (I have not yet attempted to complete the print - stopped after a few layers).

I'm currently attempting to print the left body with supports automatically generated in Cura, but that obviously adds a lot of extra material to be printed, so I thought I'd ask you if that was the design intent of that body part.

Thanks for looking at this, and again, please feel free to close if this is just a user mistake. 

Thanks,

Denis.
![left_body_hanging_pillars](https://user-images.githubusercontent.com/24587759/161436010-d2eab759-39b0-4592-a625-8956fd0470de.png)

**Comment by dgurchenkov** [comment]
Perhaps a simpler explanation is that this piece should be printed upside down?

**Comment by jurassic73** [comment]
My bad on this!  I've corrected these and uploaded them.  I swear I uploaded these in their print orientation.  You are correct.  The top surface is face down when printing.  Thanks for letting me know and sorry for any waste time.

**Comment by dgurchenkov** [comment]
Thanks! Prints perfectly now!
