### ISSUE TITLE
ISO

### ISSUE THREAD

**Issue by rubanunes** [jurassic73/split89#5]
So... any way to change the stl files to use ISO? Only three keys to edit eheh. I can deal with the QMK part

**Comment by mschneider82** [comment]
Did you managed it? Can you share,please?

**Comment by rubanunes** [comment]
I have the files now although I haven't had any time to do it and test it

**Comment by mschneider82** [comment]
Can you submit a Pull request,please? Once it is tested @jurassic73 could merge it 

I would need that iso layout too for the German layout
